AWSTemplateFormatVersion: 2010-09-09
Transform:
  - 'AWS::Serverless-2016-10-31'
Globals:
  Function:
    CodeUri: ./src
    Runtime: nodejs14.x
    MemorySize: 256
    Timeout: 15
Resources:
  SlackToken:
    Type: 'AWS::SecretsManager::Secret'
    Properties:
      Name: !Sub '${AWS::StackName}-slack-token'
      SecretString: '{"token": "added manually"}'
  Table:
    Type: 'AWS::DynamoDB::Table'
    Properties:
      AttributeDefinitions:
        - AttributeName: PK
          AttributeType: S
        - AttributeName: SK
          AttributeType: S
      KeySchema:
        - AttributeName: PK
          KeyType: HASH
        - AttributeName: SK
          KeyType: RANGE
      GlobalSecondaryIndexes:
        - IndexName: ReverseLookup
          KeySchema:
            - AttributeName: SK
              KeyType: HASH
            - AttributeName: PK
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
      BillingMode: PAY_PER_REQUEST
      StreamSpecification:
        StreamViewType: NEW_AND_OLD_IMAGES
  SaveMatchScore:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: functions/SaveMatchScore.handler
      Environment:
        Variables:
          TableName: !Ref Table
          SlackToken: '{{resolve:secretsmanager:playhem-slack-token:SecretString:token}}'
      Events:
        Submission:
          Type: EventBridgeRule
          Properties:
            InputPath: $.detail.payload.view.state.values.score_submission
            EventBusName: playhem
            Pattern:
              source:
                - slack
              detail-type:
                - view_submission
      Policies:
        - DynamoDBWritePolicy:
            TableName: !Ref Table
    Metadata:
      BuildMethod: esbuild
  ShowScoreForm:
    Type: 'AWS::Serverless::Function'
    DependsOn:
      - SlackToken
    Properties:
      Handler: functions/ShowScoreForm.handler
      Environment:
        Variables:
          SlackToken: '{{resolve:secretsmanager:playhem-slack-token:SecretString:token}}'
      Events:
        NewScore:
          Type: EventBridgeRule
          Properties:
            InputPath: $.detail
            EventBusName: playhem
            Pattern:
              source:
                - slack
              detail-type:
                - slash_command
              detail:
                text:
                  - record
                  - r
    Metadata:
      BuildMethod: esbuild
  ShowLeaderboard:
    Type: 'AWS::Serverless::Function'
    DependsOn:
      - SlackToken
    Properties:
      Handler: functions/ShowLeaderboard.handler
      Environment:
        Variables:
          SlackToken: '{{resolve:secretsmanager:playhem-slack-token:SecretString:token}}'
          TableName: !Ref Table
      Events:
        NewScore:
          Type: EventBridgeRule
          Properties:
            InputPath: $.detail
            EventBusName: playhem
            Pattern:
              source:
                - slack
              detail-type:
                - slash_command
              detail:
                text:
                  - leaderboard
                  - l
      Policies:
        - DynamoDBReadPolicy:
            TableName: !Ref Table
    Metadata:
      BuildMethod: esbuild
  WebhookReceiver:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: functions/WebhookReceiver.handler
      Events:
        PutItem:
          Type: Api
          Properties:
            Method: post
            Path: /
      Policies:
        - EventBridgePutEventsPolicy:
            EventBusName: !Ref EventBus
    Metadata:
      BuildMethod: esbuild
  EventBus:
    Type: 'AWS::Events::EventBus'
    Properties:
      Name: playhem
  PlayhemEventDiscoverer:
    Type: 'AWS::EventSchemas::Discoverer'
    Properties:
      SourceArn: !GetAtt EventBus.Arn
  TableToEvent:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: functions/TableToEvent.handler
      Runtime: nodejs14.x
      CodeUri: src/
      MemorySize: 128
      Timeout: 3
      Events:
        Table:
          Type: DynamoDB
          Properties:
            Stream: !GetAtt Table.StreamArn
            StartingPosition: TRIM_HORIZON
            BatchSize: 100
      Policies:
        - Version: 2012-10-17
          Statement:
            - Sid: Statement1
              Effect: Allow
              Action:
                - 'events:PutEvents'
              Resource:
                - !GetAtt EventBus.Arn
    Metadata:
      BuildMethod: esbuild
  CalculateRating:
    Type: 'AWS::Serverless::Function'
    Properties:
      CodeUri: src/
      Handler: functions/CalculateRating.handler
      Runtime: nodejs14.x
      Timeout: 10
      Environment:
        Variables:
          TableName: !Ref Table
      Events:
        DynamoDBEvent:
          Type: EventBridgeRule
          Properties:
            EventBusName: playhem
            InputPath: $.detail.data.new
            Pattern:
              source:
                - playhem-Table
              detail-type:
                - GAME
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref Table
    Metadata:
      BuildMethod: esbuild
  ShowMatchUpdate:
    Type: 'AWS::Serverless::Function'
    Properties:
      CodeUri: src/
      Handler: functions/ShowMatchUpdate.handler
      Runtime: nodejs14.x
      Timeout: 10
      Environment:
        Variables:
          SlackToken: '{{resolve:secretsmanager:playhem-slack-token:SecretString:token}}'
      Events:
        DynamoDBEvent:
          Type: EventBridgeRule
          Properties:
            EventBusName: playhem
            InputPath: $.detail.data.new
            Pattern:
              source:
                - playhem-Table
              detail-type:
                - GAME
    Metadata:
      BuildMethod: esbuild
  RecordRatingMetric:
    Type: 'AWS::Serverless::Function'
    Properties:
      CodeUri: src/
      Handler: functions/RecordRatingMetric.handler
      Runtime: nodejs14.x
      Timeout: 10
      Events:
        DynamoDBEvent:
          Type: EventBridgeRule
          Properties:
            EventBusName: playhem
            InputPath: $.detail.data.new
            Pattern:
              source:
                - playhem-Table
              detail-type:
                - USER
    Metadata:
      BuildMethod: esbuild
Outputs:
  EndpointUrl:
    Value: !Sub 'https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod'
